apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-important
  name: deploy-important
spec:
  replicas: 6
  selector:
    matchLabels:
      app: deploy-important
  strategy: {}
  template:
    metadata:
      labels:
        app: deploy-important
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - deploy-important
            topologyKey: 'kubernetes.io/hostname'
      containers:
      - image: nginx:1.17.6-alpine
        name: container1
      - image: busybox
        name: container2
        command: ['/bin/sh']
        args: ["-c", "sleep 30000"]
