apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container-playground
  name: multi-container-playground
spec:
  containers:
  - image: nginx:1.17.6-alpine
    name: c1
    env:
    - name: MY_NODE_NAME
      value: "multinode-demo-m02"
    volumeMounts:
      - name: varlog
        mountPath: /var/nginx
  - image: busybox:1.31.1
    name: c2
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date) >> /var/log/important.log; sleep 1; done"]
    volumeMounts:
      - name: varlog
        mountPath: /var/log
  - image: busybox:1.31.1
    name: c3
    command: ["/bin/sh"]
    args: ["-c", "tail -f /var/log/important.log"]
    volumeMounts:
      - name: varlog
        mountPath: /var/log
  volumes:
    - name: varlog
      emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
