apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: check-ip
  name: check-ip
spec:
  containers:
  - image: httpd:2.4.41-alpine
    name: check-ip
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
