apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: check-ip
  name: check-ip-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: check-ip
  type: ClusterIP
status:
  loadBalancer: {}
