apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret
  name: secret
spec:
  containers:
  - image: busybox:1.31.1
    name: secret
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 12000; done"]
    env:
    - name: APP_USER
      valueFrom:
        secretKeyRef:
          key: user
          name: secret2
    - name: APP_PASS
      valueFrom:
        secretKeyRef:
          key: pass
          name: secret2
    volumeMounts:
    - name: secret1
      mountPath: /etc/secret1
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: secret1
      secret:
        secretName: secret1
status: {}
