apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: storage-accessor
  name: storage-accessor
spec:
  containers:
  - image: alpine
    name: storage-accessor
    resources: {}
    command: ["sleep"]
    args: ["30000"]
    volumeMounts:
      - name: pv-volume
        mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: pv-volume
      persistentVolumeClaim: 
        claimName: pv-volume
status: {}
