apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ready-if-service-ready
  name: ready-if-service-ready
spec:
  containers:
  - image: nginx:1.16.1-alpine
    name: ready-if-service-ready
    resources: {}
    livenessProbe:
      exec:
        command:
          - "true"
    readinessProbe:
      exec:
        command:
          - "wget"
          - "-T2"
          - "-O-"
          - "http://check-ip-service:80"
      initialDelaySeconds: 5
      periodSeconds: 3
      failureThreshold: 2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
