apiVersion: v1
kind: Pod
metadata:
  name: nginx-kusc00401
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
        protocol: TCP
  nodeSelector:
    disk: ssd