apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: foo
  name: foo
spec:
  containers:
  - image: nginx
    name: foo
    resources: {}
  - image: busybox
    name: busybox
    resources: {}
    command: ["/bin/sh"]
    args: ["-c", "tail -n+1 -f /var/log/big-corp-app.log"]
    volumeMounts:
      - mountPath: /var/log
        name: app-data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: app-data
      emptyDir: {}
status: {}
